spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    default: prod
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false

app:
  version: @project.version@
  artifactId: @project.artifactId@
  name: @project.name@
  shortName: Demo
  longName: Demo

email:
  sendEmails: true